##***Feature Engineering & Preprocessing***

###***Feature Engineering***

In [ ]:
df['Temp_Difference'] = df['Process temperature [K]'] - df['Air temperature [K]']
df['Power'] = df['Rotational speed [rpm]'] * df['Torque [Nm]']
df.head()

In [ ]:
df["Torque_Speed_Ratio"] = df["Torque [Nm]"] / df["Rotational speed [rpm]"]
df_model["Wear_Level"] = pd.cut(
    df_model["Tool wear [min]"],
    bins=[0,100,200,300],
    labels=[0,1,2],
    include_lowest=True
)
df_model["Wear_Level"] = df_model["Wear_Level"].astype(int)

In [ ]:
df_clean = df.copy()
#These contain no predictive information - id, Prdocuct Id
#Using them causes data leakage.["TWF","HDF","PWF","OSF","RNF"]
#Your model would get fake high accuracy.
df_model = df_clean.drop(["id","Product ID","TWF","HDF","PWF","OSF","RNF"], axis=1)
df_model.drop("Failure Type", axis = 1, inplace = True)

###***Preprocessing***

In [ ]:
# Handling Missing Values & Missing Value Imputation
df.isnull().sum()

id                         0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
Temp_Difference            0
Power                      0
Failure Type               0
dtype: int64

In [ ]:
# Encode your categorical columns
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Type'] = label_encoder.fit_transform(df['Type'])

In [ ]:
# Split your data to train and test. Choose Splitting ratio wisely.
from sklearn.model_selection import train_test_split

X = df_model.drop("Machine failure", axis=1)
y = df_model["Machine failure"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify = y, random_state=42)

In [ ]:
df['Machine failure'].value_counts()

Machine failure
0    134281
1      2148
Name: count, dtype: int64

In [ ]:
df["Machine failure"].value_counts(normalize=True) * 100

Machine failure
0    98.425555
1     1.574445
Name: proportion, dtype: float64

In [ ]:
majority = 134281
minority = 2148

ratio = majority / minority
print(ratio)

62.51443202979516

In [ ]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_resm, y_train_resm = smote.fit_resample(X_train, y_train)

In [ ]:
y_train.value_counts(normalize=True)
y_test.value_counts(normalize=True)

Machine failure
0    0.984241
1    0.015759
Name: proportion, dtype: float64

In [ ]:
X_train_resm

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Temp_Difference,Power,Torque_Speed_Ratio,Wear_Level
0,2,297.200000,308.400000,1498,36.800000,101,11.200000,55126.400000,0.024566,1
1,2,299.200000,308.400000,1378,48.500000,195,9.200000,66833.000000,0.035196,1
2,1,302.400000,311.000000,1381,50.300000,203,8.600000,69464.300000,0.036423,2
3,1,298.500000,309.400000,1546,36.000000,170,10.900000,55656.000000,0.023286,1
4,1,300.000000,311.400000,1462,46.400000,187,11.400000,67836.800000,0.031737,1
...,...,...,...,...,...,...,...,...,...,...
214845,1,302.766303,310.732606,1357,54.852054,83,7.966303,74463.194477,0.040406,0
214846,1,302.776383,310.984255,1355,48.207872,82,8.207872,65354.633972,0.035560,0
214847,1,302.016766,310.808383,1355,54.392739,193,8.791617,73733.318673,0.040126,1
214848,1,298.278846,309.168830,2112,18.629126,71,10.889984,39329.552851,0.008831,0
214849,1,300.479486,310.071153,1326,60.291667,164,9.591667,79940.602557,0.045492,1

In [ ]:
y_train_resm.value_counts()

Machine failure
0    107425
1    107425
Name: count, dtype: int64